---

version: "3.6"

volumes:
  spark-workspace:
    driver: local

services:

  spark-general:
    build: ./dockers/spark_base
    image: spark-general:2.3.0

  spark-master:
    image : spark-general:2.3.0
    container_name: spark-master
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_PORT=7077 
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKLOAD=master
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_LOG=/opt/spark/logs/spark-master.out
    ports:
      - "9090:8080"
      - "7077:7077"
    command: ./bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - spark-workspace:/opt/spark-workspace


  spark-worker-1:
    image : spark-general:2.3.0
    container_name: spark-worker-1
    command: ./bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-1
    ports:
      - "9091:8080"
      - "7000:7000"
    volumes:
      - spark-workspace:/opt/spark-workspace
    depends_on:
      - spark-master
 
  spark-worker-2:
    image : spark-general:2.3.0
    container_name: spark-worker-2
    command: ./bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-2
    ports:
      - "9092:8080"
      - "7001:7000"
    volumes:
      - spark-workspace:/opt/spark-workspace
    depends_on:
      - spark-master